Repository 202306-NEA-DZ-FEW/team-a, pull requests merged in 2023-11, with the labels that each got.

#70 feat(project): create missing test files
  jest.setup.js
  src/components/BlogsCard/index.jsx
  src/components/Dashboard/ProductItem.jsx
  src/components/ItemsCarousel/__test__/ItemsCarousel.test.js
  src/components/ItemsCarousel/__test__/__snapshots__/ItemsCarousel.test.js.snap
  src/components/LandingPage/BlogsSection/BlogsSection.jsx
  src/components/LandingPage/CausesSection/index.jsx
  src/components/LandingPage/HeroSection/__test__/HeroSection.test.js
  src/components/LandingPage/HeroSection/__test__/__snapshots__/HeroSection.test.js.snap
  src/components/LandingPage/HeroSection/index.jsx
  src/components/LandingPage/OurPartnersSection/index.jsx
  src/components/LandingPage/PopularItemsSection/index.jsx
  src/components/LandingPage/StatisticsSection/index.jsx
  src/components/MemberCard/__test__/MemberCard.test.js
  src/components/MemberCard/__test__/__snapshots__/MemberCard.test.js.snap
  src/components/Navbar/__test__/LanguageFilterMenu.test.js
  src/components/Navbar/__test__/MobileMenu.test.js
  src/components/Navbar/__test__/UserMenu.test.js
  src/components/Navbar/__test__/__snapshots__/LanguageFilterMenu.test.js.snap
  src/components/Navbar/__test__/__snapshots__/MobileMenu.test.js.snap
  src/components/Navbar/__test__/__snapshots__/UserMenu.test.js.snap
  src/components/ProductCard/__test__/ProductCard.test.js
  src/components/ProductCard/__test__/__snapshots__/ProductCard.test.js.snap
  src/components/ProductDetailsCard/__test__/MobileCarousel.test.js
  src/components/ProductDetailsCard/__test__/ProductDetailsCard.test.js
  src/components/ProductDetailsCard/__test__/__snapshots__/MobileCarousel.test.js.snap
  src/components/ProductDetailsCard/__test__/__snapshots__/ProductDetailsCard.test.js.snap
  src/components/ProductDetailsCard/index.jsx
  src/components/SearchBar/__test__/SearchBar.test.js
  src/components/SearchBar/__test__/__snapshots__/SearchBar.test.js.snap
  src/components/TextAreaInput/__test__/TextAreaInput.test.js
  src/components/TextAreaInput/__test__/__snapshots__/TextAreaInput.test.js.snap
  src/components/container/__test__/Container.test.js
  src/components/container/__test__/__snapshots__/Container.test.js.snap
  src/layout/index.jsx
  src/lib/categoryArray.js
  src/lib/helpers.js
  src/pages/_document.jsx
  src/pages/blogs/[blogId].jsx
  src/pages/index.jsx
Labels: enhancement, sprint four

#75 71 fix all warning messages and imports issues
  next-i18next.config.js
  package-lock.json
  package.json
  public/images/blur.jpg
  public/images/hero.jpg
  src/components/BlogCard/__test__/BlogCard.test.js
  src/components/BlogCard/__test__/__snapshots__/BlogCard.test.js.snap
  src/components/BlogCard/index.jsx
  src/components/BlogsCard/__test__/__snapshots__/Blogs.test.js.snap
  src/components/BlogsCard/index.jsx
  src/components/ItemsCarousel/__test__/__snapshots__/ItemsCarousel.test.js.snap
  src/components/LandingPage/BlogsSection/BlogsSection.jsx
  src/components/LandingPage/BlogsSection/BlogsSectionPlaceholder.jsx
  src/components/LandingPage/BlogsSection/__test__/BlogsSection.test.js
  src/components/LandingPage/BlogsSection/__test__/__snapshots__/BlogsSection.test.js.snap
  src/components/LandingPage/HeroSection/HeroSectionPlaceholder.jsx
  src/components/LandingPage/HeroSection/__test__/__snapshots__/HeroSection.test.js.snap
  src/components/LandingPage/HeroSection/index.jsx
  src/components/LandingPage/OurPartnersSection/OurPartnersSectionPlaceholder.jsx
  src/components/LandingPage/OurPartnersSection/__test__/__snapshots__/OurPartnersSection.test.js.snap
  src/components/LandingPage/OurPartnersSection/index.jsx
  src/components/LandingPage/PopularItemsSection/PopularItemsSectionPlaceholder.jsx
  src/components/LandingPage/PopularItemsSection/__test__/PopularItemsSection.test.js
  src/components/LandingPage/PopularItemsSection/__test__/__snapshots__/PopularItemsSection.test.js.snap
  src/components/LandingPage/PopularItemsSection/index.jsx
  src/components/ProductCard/__test__/__snapshots__/ProductCard.test.js.snap
  src/components/ProductCard/index.jsx
  src/components/ProductDetailsCard/MobileCarousel.jsx
  src/components/ProductDetailsCard/__test__/__snapshots__/MobileCarousel.test.js.snap
  src/components/ProductDetailsCard/__test__/__snapshots__/ProductDetailsCard.test.js.snap
  src/components/ProductDetailsCard/index.jsx
  src/components/UserProfile/__test__/__snapshots__/UserProfile.test.js.snap
  src/components/UserProfile/index.jsx
  src/layout/index.jsx
  src/lib/helpers.js
  src/pages/_app.jsx
  src/pages/_document.jsx
  src/pages/blogs/[blogId].jsx
  src/pages/index.jsx
  src/pages/products/create/index.jsx
  src/styles/globals.css
  tailwind.config.js
Labels: sprint four

#76 style(sign in page design update): update sign in page overall design
  public/images/signIn.svg
  public/locales/ar/signIn.json
  public/locales/ar/signUp.json
  public/locales/en/signIn.json
  public/locales/en/signUp.json
  public/locales/fr/signIn.json
  public/locales/fr/signUp.json
  src/components/Checkbox/__test__/__snapshots__/Checkbox.test.js.snap
  src/components/Checkbox/index.jsx
  src/components/Input/__test__/__snapshots__/Input.test.js.snap
  src/components/Input/index.jsx
  src/components/SelectInput/__test__/__snapshots__/SelectInput.test.js.snap
  src/components/SelectInput/index.jsx
  src/components/SignInForm/ResetForm.jsx
  src/components/SignInForm/__test__/__snapshots__/ResetForm.test.js.snap
  src/components/SignInForm/__test__/__snapshots__/SignInForm.test.js.snap
  src/components/SignInForm/index.jsx
  src/components/SignUpForm/__test__/__snapshots__/SignUpForm.test.js.snap
  src/components/SignUpForm/index.jsx
  src/components/UserListItem/__test__/__snapshots__/EditItemForm.test.js.snap
  src/components/UserListItem/__test__/__snapshots__/UserListItem.test.js.snap
  src/components/UserListItems/__test__/__snapshots__/UserListItems.test.js.snap
  src/components/UserProfile/__test__/__snapshots__/UserProfile.test.js.snap
  src/components/UserProfile/__test__/__snapshots__/UserProfileEditForm.test.js.snap
  src/pages/auth/sign-in/index.jsx
Labels: enhancement, sprint four

#84 80 fix dashboard
  src/components/Navbar/UserMenu.jsx
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/Navbar/__test__/__snapshots__/UserMenu.test.js.snap
  src/components/Navbar/index.jsx
  src/components/SignUpForm/__test__/__snapshots__/SignUpForm.test.js.snap
  src/components/SignUpForm/index.jsx
  src/components/UserListItem/EditItemForm.jsx
  src/components/UserListItem/__test__/__snapshots__/EditItemForm.test.js.snap
  src/components/UserListItem/__test__/__snapshots__/UserListItem.test.js.snap
  src/components/UserListItem/index.jsx
  src/components/UserListItems/__test__/__snapshots__/UserListItems.test.js.snap
  src/components/UserListItems/index.jsx
  src/components/UserProfile/EditProfileForm.jsx
  src/components/UserProfile/__test__/EditProfileForm.test.js
  src/components/UserProfile/__test__/__snapshots__/EditProfileForm.test.js.snap
  src/components/UserProfile/__test__/__snapshots__/UserProfile.test.js.snap
  src/components/UserProfile/index.jsx
  src/pages/dashboard/index.jsx
Labels: sprint five

#91 refactor(project): fix language menu
  src/components/Carousel/CarouselItem.jsx
  src/components/Carousel/__test__/__snapshots__/Carousel.test.js.snap
  src/components/Carousel/__test__/__snapshots__/CarouselItem.test.js.snap
  src/components/Carousel/index.jsx
  src/components/Footer/__test__/__snapshots__/Footer.test.js.snap
  src/components/Footer/index.jsx
  src/components/LanguageMenu/__test__/LanguageMenu.test.js
  src/components/LanguageMenu/__test__/__snapshots__/LanguageMenu.test.js.snap
  src/components/LanguageMenu/index.jsx
  src/components/Navbar/MobileMenu.jsx
  src/components/Navbar/UserMenu.jsx
  src/components/Navbar/__test__/LanguageFilterMenu.test.js
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/Navbar/index.jsx
  src/components/Newsletter/__test__/Newsletter.test.js
  src/components/Newsletter/index.jsx
  src/components/SignInForm/__test__/__snapshots__/ResetForm.test.js.snap
  src/components/SignInForm/__test__/__snapshots__/SignInForm.test.js.snap
  src/components/SignInForm/index.jsx
  src/components/SignUpForm/__test__/__snapshots__/SignUpForm.test.js.snap
  src/components/SignUpForm/index.jsx
  src/components/Wheel/__test__/Wheel.test.js
  src/components/Wheel/__test__/__snapshots__/Wheel.test.js.snap
  src/components/Wheel/index.jsx
  src/components/Wheel/style.module.css
  src/lib/fetchCollectionWithQuery.js
  src/lib/items.js
  src/pages/auth/sign-in/index.jsx
  src/pages/auth/sign-up/index.jsx
  src/pages/blogs/index.jsx
  src/pages/items/index.jsx
  src/styles/carousel.css
Labels: enhancement, sprint six

#98 96 auth pages UI enhancement
  public/images/signin.jpg
  src/components/Checkbox/__test__/__snapshots__/Checkbox.test.js.snap
  src/components/Checkbox/index.jsx
  src/components/Input/index.jsx
  src/components/SelectInput/__test__/__snapshots__/SelectInput.test.js.snap
  src/components/SelectInput/index.jsx
  src/components/SignInForm/__test__/__snapshots__/ResetForm.test.js.snap
  src/components/SignInForm/__test__/__snapshots__/SignInForm.test.js.snap
  src/components/SignInForm/index.jsx
  src/components/SignUpForm/__test__/__snapshots__/SignUpForm.test.js.snap
  src/components/SignUpForm/index.jsx
  src/components/SignupMethods/__test__/SignupMethods.test.js
  src/components/SignupMethods/__test__/__snapshots__/SignupMethods.test.js.snap
  src/components/SignupMethods/index.jsx
  src/components/TextAreaInput/__test__/__snapshots__/TextAreaInput.test.js.snap
  src/components/TextAreaInput/index.jsx
  src/components/UserListItem/__test__/__snapshots__/EditItemForm.test.js.snap
  src/components/UserListItem/__test__/__snapshots__/UserListItem.test.js.snap
  src/components/UserListItems/__test__/__snapshots__/UserListItems.test.js.snap
  src/components/UserProfile/__test__/__snapshots__/EditProfileForm.test.js.snap
  src/components/UserProfile/__test__/__snapshots__/UserProfile.test.js.snap
  src/pages/auth/sign-in/index.jsx
  src/pages/auth/sign-up/index.jsx
  tailwind.config.js
Labels: enhancement, sprint six

#97 95 404 page UI enhancement
  public/images/404-bg.svg
  public/images/astro-man.svg
  src/components/icons/index.jsx
  src/pages/404.jsx
  src/pages/_document.jsx
  src/styles/globals.css
Labels: enhancement, sprint six

#100 refactor(success page): update design
  public/images/bell.png
  public/images/chat.png
  public/images/envelop.png
  public/images/leter.png
  public/images/like.png
  src/pages/success.jsx
Labels: enhancement, sprint six

#104 fix(project): change the color palette
  src/components/Input/__test__/__snapshots__/Input.test.js.snap
  src/components/Input/index.jsx
  src/components/Items/Filters/CategoryFilter.jsx
  src/components/Items/Filters/ClearFilterButton.jsx
  src/components/Items/Filters/ListingTypeFilter.jsx
  src/components/Items/Filters/LocationFilter.jsx
  src/components/Items/Filters/Pagination.jsx
  src/components/Items/Filters/__test__/__snapshots__/CategoryFilter.test.js.snap
  src/components/Items/Filters/__test__/__snapshots__/ClearFilterButton.test.js.snap
  src/components/Items/Filters/__test__/__snapshots__/ListingTypeFilter.test.js.snap
  src/components/Items/Filters/__test__/__snapshots__/LocationFilter.test.js.snap
  src/components/Items/Filters/__test__/__snapshots__/Pagination.test.js.snap
  src/components/Items/index.jsx
  src/components/LanguageMenu/index.jsx
  src/components/Newsletter/__test__/__snapshots__/Newsletter.test.js.snap
  src/components/Newsletter/__test__/__snapshots__/NewsletterForm.test.js.snap
  src/components/SearchBar/__test__/__snapshots__/SearchBar.test.js.snap
  src/components/SearchBar/index.jsx
  src/components/SelectInput/__test__/__snapshots__/SelectInput.test.js.snap
  src/components/SelectInput/index.jsx
  src/components/SignInForm/__test__/__snapshots__/ResetForm.test.js.snap
  src/components/SignInForm/__test__/__snapshots__/SignInForm.test.js.snap
  src/components/SignUpForm/__test__/__snapshots__/SignUpForm.test.js.snap
  src/components/TextAreaInput/__test__/__snapshots__/TextAreaInput.test.js.snap
  src/components/TextAreaInput/index.jsx
  src/components/UserListItem/__test__/__snapshots__/EditItemForm.test.js.snap
  src/components/UserListItem/__test__/__snapshots__/UserListItem.test.js.snap
  src/components/UserListItem/index.jsx
  src/components/UserListItems/__test__/__snapshots__/UserListItems.test.js.snap
  src/components/UserListItems/index.jsx
  src/components/UserProfile/__test__/__snapshots__/EditProfileForm.test.js.snap
  src/components/UserProfile/__test__/__snapshots__/UserProfile.test.js.snap
  src/components/UserProfile/index.jsx
  src/pages/_document.jsx
  tailwind.config.js
Labels: enhancement, sprint six

#106 style(auth pages): fix overflow
  public/locales/en/signUp.json
  src/components/SignInForm/__test__/__snapshots__/ResetForm.test.js.snap
  src/components/SignInForm/__test__/__snapshots__/SignInForm.test.js.snap
  src/components/SignInForm/index.jsx
  src/components/SignUpForm/__test__/__snapshots__/SignUpForm.test.js.snap
  src/components/SignUpForm/index.jsx
  src/pages/auth/sign-in/index.jsx
  src/pages/auth/sign-up/index.jsx
Labels: enhancement, sprint six

#102 refactor(about page): enhancing MemberSection
  package-lock.json
  package.json
  public/images/bouchra.jpg
  public/images/dz.svg
  public/images/farouk.png
  public/images/h.jpg
  public/images/riadh-mouamnia.jpg
  public/images/sorour.jpg
  public/locales/ar/about.json
  public/locales/en/about.json
  public/locales/fr/about.json
  public/locales/tr/about.json
  src/components/Map/__test__/Map.test.js
  src/components/Map/__test__/__snapshots__/Map.test.js.snap
  src/components/Map/index.jsx
  src/components/MemberCard/styles.module.css
  src/lib/teamMembers.js
  src/pages/about/index.jsx
Labels: enhancement, sprint six

#108 107 blogs page UI update
  public/images/blogsillustration.svg
  public/locales/ar/blogs.json
  public/locales/ar/common.json
  public/locales/ar/landingPage.json
  public/locales/en/blogs.json
  public/locales/en/common.json
  public/locales/en/landingPage.json
  public/locales/fr/blogs.json
  public/locales/fr/common.json
  public/locales/fr/landingPage.json
  public/locales/tr/blogs.json
  public/locales/tr/common.json
  public/locales/tr/landingPage.json
  src/components/BlogCard/HorizontalCard.jsx
  src/components/BlogCard/__test__/__snapshots__/BlogCard.test.js.snap
  src/components/BlogCard/index.jsx
  src/components/BlogsCard/__test__/__snapshots__/Blogs.test.js.snap
  src/components/BlogsCard/index.jsx
  src/components/ItemDetailsCard/__test__/__snapshots__/ItemDetailsCard.test.js.snap
  src/components/ItemDetailsCard/index.jsx
  src/components/LandingPage/BlogsSection/BlogsSection.jsx
  src/components/LandingPage/BlogsSection/__test__/__snapshots__/BlogsSection.test.js.snap
  src/components/LandingPage/StatisticsSection/__test__/__snapshots__/StatisticsSection.test.js.snap
  src/components/container/index.jsx
  src/pages/blogs/[blogId].jsx
  src/pages/blogs/index.jsx
  src/pages/index.jsx
Labels: enhancement, sprint six

#115 Develop
  public/locales/ar/common.json
  public/locales/en/common.json
  public/locales/fr/common.json
  public/locales/tr/common.json
  src/components/Carousel/CarouselPlaceholder.jsx
  src/components/ItemDetailsCard/__test__/__snapshots__/ItemDetailsCard.test.js.snap
  src/components/ItemDetailsCard/index.jsx
  src/components/UserListItems/__test__/__snapshots__/UserListItems.test.js.snap
  src/components/UserListItems/index.jsx
Labels: enhancement

#117 feat(project): fix newsletter font and "read more" button
  public/locales/en/addItem.json
  src/components/BlogCard/HorizontalCard.jsx
  src/components/BlogCard/index.jsx
  src/components/BlogsCard/index.jsx
  src/components/Footer/__test__/__snapshots__/Footer.test.js.snap
  src/components/Footer/index.jsx
  src/components/LandingPage/BlogsSection/index.jsx
  src/components/Newsletter/NewsletterForm.jsx
  src/components/Newsletter/__test__/__snapshots__/Newsletter.test.js.snap
  src/components/Newsletter/__test__/__snapshots__/NewsletterForm.test.js.snap
  src/context/AuthProvider.jsx
Labels: enhancement
