Repository 202306-NEA-DZ-FEW/team-a, pull requests merged in 2023-10, with the labels that each got.

#25 Partners Section
  public/images/flatironschool2.png
  public/images/mepi1.png
  public/images/microsoft4.png
  public/images/recoded3.png
  src/components/LandingPage/OurPartnersSection/__test__/OurPartnersSection.test.js
  src/components/LandingPage/OurPartnersSection/__test__/__snapshots__/OurPartnersSection.test.js.snap
  src/components/LandingPage/OurPartnersSection/index.jsx
Labels: enhancement

#27 refactor(project): refactor the landing page and add internationaliza…
  public/locales/ar/common.json
  public/locales/ar/landingPage.json
  public/locales/en/common.json
  public/locales/en/landingPage.json
  public/locales/fr/common.json
  public/locales/fr/landingPage.json
  src/components/BlogCard/__test__/__snapshots__/BlogCard.test.js.snap
  src/components/BlogCard/index.jsx
  src/components/Footer/__test__/__snapshots__/Footer.test.js.snap
  src/components/Footer/index.jsx
  src/components/LandingPage/BlogsSection/BlogsSection.jsx
  src/components/LandingPage/BlogsSection/__test__/__snapshots__/BlogsSection.test.js.snap
  src/components/LandingPage/CausesSection/__test__/__snapshots__/CausesSection.test.js.snap
  src/components/LandingPage/CausesSection/index.jsx
  src/components/LandingPage/HeroSection/HeroIllustration.jsx
  src/components/LandingPage/HeroSection/HeroText.jsx
  src/components/LandingPage/HeroSection/__test__/__snapshot__/__snapshots__/HeroSection.test.js.snap
  src/components/LandingPage/HeroSection/index.jsx
  src/components/LandingPage/InfoCard/__test__/__snapshots__/InfoCard.test.js.snap
  src/components/LandingPage/InfoCard/index.jsx
  src/components/LandingPage/OurPartnersSection/__test__/__snapshots__/OurPartnersSection.test.js.snap
  src/components/LandingPage/OurPartnersSection/index.jsx
  src/components/LandingPage/PopularItemsSection/__test__/__snapshots__/PopularItemsSection.test.js.snap
  src/components/LandingPage/PopularItemsSection/index.jsx
  src/components/LandingPage/StatisticsSection/__test__/__snapshots__/StatisticsSection.test.js.snap
  src/components/LandingPage/StatisticsSection/index.jsx
  src/components/Navbar/LanguageFilterMenu.jsx
  src/components/Navbar/MobileMenu.jsx
  src/components/Navbar/UserMenu.jsx
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/Navbar/index.jsx
  src/components/container/index.jsx
  src/layout/Layout.jsx
  src/pages/_app.jsx
  src/pages/index.jsx
Labels: enhancement, sprint-one

#36 28 authentication setup
  __mocks__/next/router.js
  i18n-testing.js
  jest.setup.js
  public/images/profile.svg
  public/images/spinner.svg
  public/images/stats.svg
  public/locales/ar/dashboard.json
  public/locales/ar/signIn.json
  public/locales/ar/signUp.json
  public/locales/en/dashboard.json
  public/locales/en/signIn.json
  public/locales/en/signUp.json
  public/locales/fr/dashboard.json
  public/locales/fr/signIn.json
  public/locales/fr/signUp.json
  src/components/BlogCard/__test__/__snapshots__/BlogCard.test.js.snap
  src/components/Footer/__test__/__snapshots__/Footer.test.js.snap
  src/components/Input/index.jsx
  src/components/LandingPage/BlogsSection/__test__/__snapshots__/BlogsSection.test.js.snap
  src/components/LandingPage/CausesSection/__test__/__snapshots__/CausesSection.test.js.snap
  src/components/LandingPage/HeroSection/__test__/__snapshot__/__snapshots__/HeroSection.test.js.snap
  src/components/LandingPage/InfoCard/__test__/__snapshots__/InfoCard.test.js.snap
  src/components/LandingPage/OurPartnersSection/__test__/__snapshots__/OurPartnersSection.test.js.snap
  src/components/LandingPage/PopularItemsSection/__test__/__snapshots__/PopularItemsSection.test.js.snap
  src/components/LandingPage/StatisticsSection/__test__/__snapshots__/StatisticsSection.test.js.snap
  src/components/Navbar/LanguageFilterMenu.jsx
  src/components/Navbar/MobileMenu.jsx
  src/components/Navbar/__test__/Navbar.test.js
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/Navbar/index.jsx
  src/components/ProductCard/__test__/__snapshots__/ProductCard.test.js.snap
  src/components/SIgnUpFrom/index.jsx
  src/components/SignInForm/index.jsx
  src/components/UserListItems/index.jsx
  src/components/UserProfile/index.jsx
  src/context/AuthProvider.jsx
  src/layout/index.jsx
  src/pages/404.jsx
  src/pages/_app.jsx
  src/pages/auth/sign-in/index.jsx
  src/pages/auth/sign-up/index.jsx
  src/pages/dashboard/index.jsx
  src/pages/index.jsx
Labels: enhancement, sprint two

#39 feat(project): add translation files for states
  public/locales/ar/states.json
  public/locales/en/states.json
  public/locales/fr/states.json
  src/components/LandingPage/OurPartnersSection/__test__/OurPartnersSection.test.js
  src/components/Navbar/__test__/Navbar.test.js
  src/components/SIgnUpFrom/index.jsx
  src/lib/firebase.js
  src/lib/getAllStates.js
  src/pages/auth/sign-up/index.jsx
Labels: enhancement

#41 feat(sign up page): create sign up page and its appropriate test
  public/locales/ar/signUp.json
  public/locales/ar/states.json
  public/locales/en/signUp.json
  public/locales/en/states.json
  public/locales/fr/signUp.json
  public/locales/fr/states.json
  src/components/Input/__test__/__snapshots__/Input.test.js.snap
  src/components/Input/index.jsx
  src/components/SIgnUpFrom/index.jsx
  src/components/SelectInput/__test__/__snapshots__/SelectInput.test.js.snap
  src/components/SelectInput/index.jsx
  src/components/SignUpForm/__test__/SignUpForm.test.js
  src/components/SignUpForm/__test__/__snapshots__/SignUpForm.test.js.snap
  src/components/SignUpForm/index.jsx
  src/lib/getAllStates.js
  src/pages/auth/sign-up/index.jsx
Labels: enhancement

#42 dashboard
  public/locales/ar/dashboard.json
  public/locales/en/dashboard.json
  public/locales/fr/dashboard.json
  src/components/UserListItem/__test__/UserListItem.test.js
  src/components/UserListItem/__test__/__snapshots__/UserListItem.test.js.snap
  src/components/UserListItem/index.jsx
  src/components/UserListItems/__test__/UserListItems.test.js
  src/components/UserListItems/__test__/__snapshots__/UserListItems.test.js.snap
  src/components/UserListItems/index.jsx
  src/components/UserProfile/__test__/UserProfile.test.js
  src/components/UserProfile/__test__/__snapshots__/UserProfile.test.js.snap
  src/components/UserProfile/index.jsx
  src/pages/dashboard/index.jsx
Labels: enhancement

#44 fix(project): fix font family
  src/components/Footer/__test__/__snapshots__/Footer.test.js.snap
  src/components/Footer/index.jsx
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/Navbar/index.jsx
  src/layout/index.jsx
  src/pages/_app.jsx
  src/pages/_document.jsx
Labels: bug, sprint two

#45 33 sign up functionality
  src/components/Navbar/UserMenu.jsx
  src/components/Navbar/__test__/Navbar.test.js
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/Navbar/index.jsx
  src/components/SignUpForm/__test__/SignUpForm.test.js
  src/components/SignUpForm/__test__/__snapshots__/SignUpForm.test.js.snap
  src/components/SignUpForm/index.jsx
  src/context/AuthProvider.jsx
  src/layout/index.jsx
  src/lib/firebase.js
  src/pages/dashboard/index.jsx
Labels: enhancement, sprint two

#57 52 products page
  package-lock.json
  package.json
  src/components/Carousel/CarouselItem.jsx
  src/components/Carousel/__test__/Carousel.test.js
  src/components/Carousel/__test__/CarouselItem.test.js
  src/components/Carousel/__test__/__snapshots__/Carousel.test.js.snap
  src/components/Carousel/__test__/__snapshots__/CarouselItem.test.js.snap
  src/components/Carousel/index.jsx
  src/components/LandingPage/PopularItemsSection/__test__/__snapshots__/PopularItemsSection.test.js.snap
  src/components/Navbar/LanguageFilterMenu.jsx
  src/components/Navbar/MobileMenu.jsx
  src/components/Navbar/UserMenu.jsx
  src/components/ProductCard/__test__/__snapshots__/ProductCard.test.js.snap
  src/components/ProductCard/index.jsx
  src/components/ProductFiltering/CategoryCard.jsx
  src/components/ProductFiltering/ClearFilterButton.jsx
  src/components/ProductFiltering/LocationFilter.jsx
  src/components/ProductFiltering/SliderRow.jsx
  src/components/ProductFiltering/__test__/CategoryCard.test.js
  src/components/ProductFiltering/__test__/ClearFilterButton.test.js
  src/components/ProductFiltering/__test__/LocationFilter.test.js
  src/components/ProductFiltering/__test__/SliderRow.test.js
  src/components/ProductFiltering/__test__/__snapshots__/CategoryCard.test.js.snap
  src/components/ProductFiltering/__test__/__snapshots__/ClearFilterButton.test.js.snap
  src/components/ProductFiltering/__test__/__snapshots__/LocationFilter.test.js.snap
  src/components/ProductFiltering/__test__/__snapshots__/SliderRow.test.js.snap
  src/components/SearchBar/index.jsx
  src/components/SelectInput/index.jsx
  src/components/SignUpForm/__test__/__snapshots__/SignUpForm.test.js.snap
  src/lib/categoryArray.js
  src/lib/fetchCollection.js
  src/lib/firebase.js
  src/lib/getAllCategories.js
  src/lib/getAllStates.js
  src/pages/_app.jsx
  src/pages/products/index.jsx
  src/styles/carousel.css
  src/styles/globals.css
Labels: enhancement, sprint three

#60 47 blogs page
  public/locales/ar/blogs.json
  public/locales/en/blogs.json
  public/locales/fr/blogs.json
  src/components/BlogsCard/__test__/Blogs.test.js
  src/components/BlogsCard/__test__/__snapshots__/Blogs.test.js.snap
  src/components/BlogsCard/index.jsx
  src/lib/fetchFirebaseCollection.js
  src/pages/blogs/index.jsx
Labels: enhancement, sprint three
